<?php
/**
 * WorkflowElementReference
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * WorkflowElementReference Class Doc Comment
 *
 * @category Class
 * @description A reference to the location of the error. This will be null if the error does not refer to a specific element.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WorkflowElementReference implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WorkflowElementReference';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'property_key' => 'string',
        'rule_id' => 'string',
        'status_mapping_reference' => '\OpenAPI\Client\Model\ProjectAndIssueTypePair',
        'status_reference' => 'string',
        'transition_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'property_key' => null,
        'rule_id' => null,
        'status_mapping_reference' => null,
        'status_reference' => null,
        'transition_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'property_key' => false,
		'rule_id' => false,
		'status_mapping_reference' => false,
		'status_reference' => false,
		'transition_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'property_key' => 'propertyKey',
        'rule_id' => 'ruleId',
        'status_mapping_reference' => 'statusMappingReference',
        'status_reference' => 'statusReference',
        'transition_id' => 'transitionId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'property_key' => 'setPropertyKey',
        'rule_id' => 'setRuleId',
        'status_mapping_reference' => 'setStatusMappingReference',
        'status_reference' => 'setStatusReference',
        'transition_id' => 'setTransitionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'property_key' => 'getPropertyKey',
        'rule_id' => 'getRuleId',
        'status_mapping_reference' => 'getStatusMappingReference',
        'status_reference' => 'getStatusReference',
        'transition_id' => 'getTransitionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('property_key', $data ?? [], null);
        $this->setIfExists('rule_id', $data ?? [], null);
        $this->setIfExists('status_mapping_reference', $data ?? [], null);
        $this->setIfExists('status_reference', $data ?? [], null);
        $this->setIfExists('transition_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets property_key
     *
     * @return string|null
     */
    public function getPropertyKey()
    {
        return $this->container['property_key'];
    }

    /**
     * Sets property_key
     *
     * @param string|null $property_key A property key.
     *
     * @return self
     */
    public function setPropertyKey($property_key)
    {

        if (is_null($property_key)) {
            throw new \InvalidArgumentException('non-nullable property_key cannot be null');
        }

        $this->container['property_key'] = $property_key;

        return $this;
    }

    /**
     * Gets rule_id
     *
     * @return string|null
     */
    public function getRuleId()
    {
        return $this->container['rule_id'];
    }

    /**
     * Sets rule_id
     *
     * @param string|null $rule_id A rule ID.
     *
     * @return self
     */
    public function setRuleId($rule_id)
    {

        if (is_null($rule_id)) {
            throw new \InvalidArgumentException('non-nullable rule_id cannot be null');
        }

        $this->container['rule_id'] = $rule_id;

        return $this;
    }

    /**
     * Gets status_mapping_reference
     *
     * @return \OpenAPI\Client\Model\ProjectAndIssueTypePair|null
     */
    public function getStatusMappingReference()
    {
        return $this->container['status_mapping_reference'];
    }

    /**
     * Sets status_mapping_reference
     *
     * @param \OpenAPI\Client\Model\ProjectAndIssueTypePair|null $status_mapping_reference status_mapping_reference
     *
     * @return self
     */
    public function setStatusMappingReference($status_mapping_reference)
    {

        if (is_null($status_mapping_reference)) {
            throw new \InvalidArgumentException('non-nullable status_mapping_reference cannot be null');
        }

        $this->container['status_mapping_reference'] = $status_mapping_reference;

        return $this;
    }

    /**
     * Gets status_reference
     *
     * @return string|null
     */
    public function getStatusReference()
    {
        return $this->container['status_reference'];
    }

    /**
     * Sets status_reference
     *
     * @param string|null $status_reference A status reference.
     *
     * @return self
     */
    public function setStatusReference($status_reference)
    {

        if (is_null($status_reference)) {
            throw new \InvalidArgumentException('non-nullable status_reference cannot be null');
        }

        $this->container['status_reference'] = $status_reference;

        return $this;
    }

    /**
     * Gets transition_id
     *
     * @return string|null
     */
    public function getTransitionId()
    {
        return $this->container['transition_id'];
    }

    /**
     * Sets transition_id
     *
     * @param string|null $transition_id A transition ID.
     *
     * @return self
     */
    public function setTransitionId($transition_id)
    {

        if (is_null($transition_id)) {
            throw new \InvalidArgumentException('non-nullable transition_id cannot be null');
        }

        $this->container['transition_id'] = $transition_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


